### PR TITLE
Fixed support for esm

### PR DESCRIPTION
**Pull request by swernerx**
- Updates GitHub matrix to respect only modern NodeJS LTS versions
- Removed travis config + bower config (assumption is that these are not relevant anymore)
- Replaced CJS code entry points (require) with ESM syntax
- Updated dependencies to the newest versions
- Tests are all green
- Fixes support for Vite bundler

### CODE REVIEW

**Comment by mcdado** [comment]
Hi there, thank you!

The CI job won’t run against the PR with Github Actions? IIRC with travis it used to run as a PR check.

**Comment by mcdado** [comment]
I see that previous runs “failed” because windows-2016 is deprecated. Can you switch to windows-2019 and windows-latest only, please?

**Comment by alexnault** [comment]
Hey! Any progress on this? We are having issues using moment-business-days in a project configured with Vite (esbuild/rollup) since this package doesn't properly support ESM.

**Comment by borislit** [comment]
@mcdado was this ever released?

**Pull request merged**
