### PR TITLE
Fix infinite loop caused by fraction value in businessAdd (fixes #55)

### LINKED ISSUE #55: Fractional day causes infinite loop in businessAdd
Run test that calls businessAdd with a fractional number of days:

      it('adds business days only, excluding weekends, handles fractional days without infinite loop ', function (done) {
        var newBusinessDay = moment('11-03-2015 12:42:00', 'MM-DD-YYYY hh-mm-ss').businessAdd(10.5);
        expect(newBusinessDay.format('D')).to.eql('17');
        done();
      });
$ npm test

> moment-business-days@1.0.6 test XXXXXX\moment-business-days
> mocha tests/*

   Moment Business Days
    .prevBusinessDay
      When today is Monday
        √ should be Friday
    .isBusinessDay
      When today is a regular weekday
        √ should be true
      When today is a weekend
        √ should be false
      When today is a holiday determined by a function
        √ should be false
      When today is custom working day
        √ Should be true
      When today is a holiday
        √ should be false
    .businessDaysIntoMonth
      When moment object is invalid
        √ should return NaN
      On Wednesday, September 23rd 2015
        √ should be 17 when there are no holidays
        √ should be 16 when considering labor day
    .businessAdd
      When moment object is invalid
        √ should return a new invalid moment object
      On Tuesday, November 3rd 2015
        √ adds business days only, excluding weekends, even over 2 weeks
        √ adds business days only, excluding weekends

(test hangs here)

Cause: once the remaining variable goes negative, due to the fractional day, the while loop never terminates. It needs to test if remaining is > 0.

I'm not sure if you want to support this use case, throw an error, or silently ignore the fraction. I have a pull request ready if you want the latter.

### PR DESCRIPTION
**Pull request by avenue19**
Sorry, my first PR and I uploaded one entire file instead of editing on web. I wasn't able to push from my local clone due to proxy issue.

### CODE REVIEW

**Comment by mcdado** [comment]
Hi, thanks for sending the PR! I see that there are problems with whitespace causing the whole file to diff (you can see it by going to the "Files changed" tab in this PR page and on the right open "Diff settings" and select "Hide whitespace changes".

Anyway, I'll review it and in case fix the problems 😉

**Comment by mcdado** [comment]
> I think it was my error causing the whole file diff. I'm a github newbie :/ Thanks for your patience; )

Hey we all were newbie at some point, I sure made similar mistakes in the beginning! 😉 
About the diff, as I mentioned the problem is with line endings. If you don't mind I can fix both problems for you and add the absolute value rounding.

**Comment by avenue19** [comment]
Yes, please fix as necessary.

**Comment by kalmecak** [comment]
Thanks guys, I've deployed it to NPM, I'm closing this issue.

**Comment by nbkhope** [comment]
Was there a reason why you reset the original date's timestamp when do you `businessAdd()`? I have a project that relies on it, some test started failing and we realized this new version now resets the timestamp because of this line

https://github.com/kalmecak/moment-business-days/pull/59/files#diff-168726dbe96b3ce427e7fedce31bb0bcR74

**Comment by avenue19** [comment]
Hi Renan, sorry, that wasn't intentional. I just added a PR to fix.
Jerry

**Comment by mcdado** [comment]
> Was there a reason why you reset the original date's timestamp when do you `businessAdd()`? I have a project that relies on it, some test started failing and we realized this new version now resets the timestamp because of this line

Sorry, this slipped through review. Do you have some of those tests to contribute this library? That would be great. @avenue19 did add one, the more the better I guess… 😅

**Pull request merged**
