### PR TITLE
ci(workflows): add continuous integration action

### PR DESCRIPTION
**Pull request by oleg-koval**
Adds Github actions continuous integration

Runs test on matrix of different operational systems and node.js versions:

Systems:
- macOS-10.14
- windows-2016
- ubuntu-latest

Node.js versions:
- 4
- 6
- 8
- 10
- 12

Example of run can be found in my fork:

- https://github.com/oleg-koval/moment-business-days/pull/2
- https://github.com/oleg-koval/moment-business-days/actions

### CODE REVIEW

**Comment by mcdado** [comment]
What needs to be done now to get actions?

**Comment by oleg-koval** [comment]
@mcdado you need to enable them in Settings -> Actions -> Enable local & third party Actions for this repository

**Comment by mcdado** [comment]
I think only the owner @kalmecak can do it... btw we could talk of moving transferring the ownership of the repo / npm package since @kalmecak doesn't seem very partecipative anymore, which I understand.

**Comment by oleg-koval** [comment]
@mcdado sent an email to @kalmecak , waiting for a response

**Pull request merged**
